Added smoke tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -350,51 +350,111 @@ jobs:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - revert-migrations:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-          
-# Perform simple tests on both frontend and backend
-  # smoke-test:
+
+  # Perform simple tests on both frontend and backend
+  smoke-test:
+    docker:
+      - image: python:3.10-alpine3.16
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache curl aws-cli tar gzip nodejs npm
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Backend smoke test.
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            # curl -s http://google.com
+            # curl "${API_URL}/api/status"
+            if curl "${API_URL}/api/status"
+            then
+                return 0
+            else
+                return 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            export URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com/#/employees"
+            echo ${URL}
+            if curl -s $URL | grep "Welcome"
+            then
+              # Change this to 0 after the job fails
+              exit  1
+            else
+              exit  1
+            fi
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+
+  # # Once smoke tests pass, proceed to switch from blue to green
+  # cloudfront-update:
   #   docker:
-  #     - image: python:3.10-alpine3.16
+  #     # Docker image here that supports AWS CLI
+  #     - image: amazon/aws-cli
   #   steps:
+  #     # Checkout code from git
   #     - checkout
   #     - run:
   #         name: Install dependencies
   #         command: |
-  #           apk add --update --no-cache curl aws-cli tar gzip nodejs npm
-  #     - attach_workspace:
-  #         at: ~/
+  #           yum install tar gzip npm nodejs -y
   #     - run:
-  #         name: Backend smoke test.
+  #         name: Backup Previous Workflow ID
   #         command: |
-  #           export BACKEND_IP=$(aws ec2 describe-instances \
-  #           --query 'Reservations[*].Instances[*].PublicIpAddress' \
-  #           --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
-  #           --output text)
-  #           export API_URL="http://${BACKEND_IP}:3030"
-  #           echo "${API_URL}"
-  #           # curl "${API_URL}/api/status"
-  #           if curl -s http://google.com
-  #           then
-  #               return 0
-  #           else
-  #               return 1
-  #           fi
+  #           export OLD_WORKFLOW_ID=$(aws cloudformation 
+  #                   list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+  #                   --no-paginate --output text)
+  #           echo $OLD_WORKFLOW_ID >> ~/OldWorkflowID.txt
+  #           cat ~/OldWorkflowID.txt
+  #           curl https://kvdb.io/2AKWdi2EmvWwVyoYEQsov6/previous_id -d "${OLD_WORKFLOW_ID}"
   #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           export URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com/#/employees"
-  #           echo ${URL}
-  #           if curl -s $URL | grep "Welcome"
-  #           then
-  #             # Change this to 0 after the job fails
-  #             exit  1
-  #           else
-  #             exit  1
-  #           fi
+  #         name: Update cloudfront distribution
+  #         command: |  
+  #           aws cloudformation deploy \
+  #             --template-file .circleci/files/cloudfront.yml \
+  #             --stack-name InitialStack \
+  #             --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7} \
+  #             --tags project=udapeople
+  #           echo Previous Workflow ID:$OLD_WORKFLOW_ID
+  #           echo Current Workflow ID: ${CIRCLE_WORKFLOW_ID:0:7}
+  #     # Here's where you will add some code to rollback on failure
   #     - destroy-environment:
   #         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
   #     - revert-migrations:
   #         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+
+
+  # cleanup:
+  #   docker:
+  #     # Docker image here
+  #     - image: amazon/aws-cli
+  #   steps:
+  #     # Checkout code from git
+  #     - checkout
+  #     - run:
+  #         name: Get old stack workflow id
+  #         command: |
+  #           # your code here
+  #           export OldWorkflowID="the id here"
+  #           export STACKS=[] #put the list of stacks here
+  #     - run:
+  #         name: Remove old stacks and files
+  #         command: |
+  #           if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+  #           then
+  #             # your code here
+  #           fi
 
 
 
@@ -424,3 +484,5 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
