Added deploy frontend & backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,22 +28,26 @@ commands:
             aws cloudformation delete-stack \
             --stack-name udapeople-frontend-<<parameters.workflow_id>>
 
+  # Trigger rollback jobs if the smoke tests or any following jobs fail, or
+  # Revert the last migration, if a new migration was applied
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
+    description: Revert the last migration
     parameters:
-      # Add parameter here
       workflow_id:
         type: string
     steps:
       - run:
           name: Revert migrations
           when: on_fail
-          # Add when this will run
           command: |
-            cd ~/project/backend
-            npm install
-            npm run build
-            npm run migrations:revert
+            SUCCESS=$(curl --insecure https://kvdb.io/2AKWdi2EmvWwVyoYEQsov6/migration_${CIRCLE_WORKFLOW_ID:0:7})
+            if (( $SUCCESS == 1 ));
+            then
+              cd ~/project/backend
+              npm install
+              npm run build
+              npm run migrations:revert
+            fi
 
 jobs:
 # Compile the frontend
@@ -242,15 +246,13 @@ jobs:
 # Runs db migrations so that new changes are applied
   run-migrations:
     docker:
-      - image: cimg/node:13.8.0
+      - image: python:3.10-alpine3.16
     steps:
       - checkout
       - run:
-          name: Install AWS CLI
+          name: Install Dependencies
           command: |
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
+            apk add --update --no-cache tar gzip nodejs npm aws-cli curl
       - restore_cache:
           keys: [backend-build]      
       - run:
@@ -258,6 +260,7 @@ jobs:
           command: |
             cd backend
             npm install
+            npm run build
             npm run migrations > migrations_dump.txt
             cat migrations_dump.txt
       - run:
@@ -265,7 +268,7 @@ jobs:
           command: |
             if grep -q "has been executed successfully" ~/project/backend/migrations_dump.txt
             then
-              curl https://kvdb.io/2AKWdi2EmvWwVyoYEQsov6/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              curl   -d '1'
             fi
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
@@ -347,10 +350,11 @@ jobs:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - revert-migrations:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-
+          
+# Perform simple tests on both frontend and backend
   # smoke-test:
   #   docker:
-  #     # Lightweight Docker image 
+  #     - image: python:3.10-alpine3.16
   #   steps:
   #     - checkout
   #     - run:
@@ -359,10 +363,6 @@ jobs:
   #           apk add --update --no-cache curl aws-cli tar gzip nodejs npm
   #     - attach_workspace:
   #         at: ~/
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           # your code here
   #     - run:
   #         name: Backend smoke test.
   #         command: |
@@ -382,10 +382,12 @@ jobs:
   #     - run:
   #         name: Frontend smoke test.
   #         command: |
-  #           FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com
-  #           if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+  #           export URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com/#/employees"
+  #           echo ${URL}
+  #           if curl -s $URL | grep "Welcome"
   #           then
-  #             exit  0
+  #             # Change this to 0 after the job fails
+  #             exit  1
   #           else
   #             exit  1
   #           fi
@@ -393,7 +395,6 @@ jobs:
   #         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
   #     - revert-migrations:
   #         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-  #     # Here's where you will add some code to rollback on failure  
 
 
 
